import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col items-center mx-auto mt-6 mb-20 bg-slate-100`}>
        <main className="flex-auto min-w-0 flex flex-col px-6 sm:px-4 md:px-0 max-w-[1024px] w-full bg-slate-100">
          {children}
        </main>
      </body>
    </html>
  );
}
